### ISSUE TITLE
Run without context index

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/AGDISTIS#49]
Make the master run also without context index.

**Comment by DiegoMoussallem** [comment]
Just to set `context=fase` in agdistis.properties file. Could you close it?

**Comment by RicardoUsbeck** [comment]
Need to test it first, consider it staging and leave it open

**Comment by DiegoMoussallem** [comment]
@RicardoUsbeck Ah OK. In case you want to have a look. I have done a test in https://github.com/dice-group/AGDISTIS/blob/master/src/test/java/AGDISTISTest.java#L83
If you disable context i.e., `context=false` the test will fail which means that works without context, but if you enable i.e., `context=true` it will pass.

**Comment by RicardoUsbeck** [comment]
Closed by fccc311c408571e2b60b639b3ecd7ed5b0dc558e
