### ISSUE TITLE
Update docker hub image

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/AGDISTIS#58]
Hi @yamalight 

I will work today on AGDISTIS/MAG and update the issues etc. 

Can you afterwards please update https://hub.docker.com/r/aksw/agdistis/ ?

**Comment by yamalight** [comment]
@RicardoUsbeck it's autobuilds from master :)

**Comment by RicardoUsbeck** [comment]
Is there a way to make the description more pretty?

**Comment by yamalight** [comment]
@RicardoUsbeck if you tell me your hub username - I can add you as admin so you can edit it

**Comment by yamalight** [comment]
on other note - shall we move the image from `aksw/AGDISTIS` to `dicegroup/AGDISTIS`?

**Comment by RicardoUsbeck** [comment]
Maybe not now but as an enhancement ticket because it would break a lot of documentation and just stuff

**Comment by yamalight** [comment]
We can also push image to both tags

**Comment by RicardoUsbeck** [comment]
Then let's do that!

**Comment by yamalight** [comment]
Done in https://github.com/dice-group/AGDISTIS/commit/2eb7b4112f949d07cf23c16eb5618160ef01884b
