### ISSUE TITLE
Creation of the context index very slow.

### ISSUE THREAD

**Issue by DiegoMoussallem** [dice-group/AGDISTIS#66]
To improve the code of context index, it is quite slow, for example, it is taking 1 full day for English.

**Comment by RicardoUsbeck** [comment]
I think  we need to switch to Elastic Search (wikidata overflow issue) or to https://github.com/dice-group/autoindex soon anyway. I am currently looking for a student to do the transformation.

**Comment by DiegoMoussallem** [comment]
It is an amazing idea. Maybe I have a student for that, but just from July on. Let's talk.

**Comment by DiegoMoussallem** [comment]
New index was created by @vdanielupb
