### ISSUE TITLE
German version links 

### ISSUE THREAD

**Issue by renespeck** [dice-group/AGDISTIS#72]
The German endpoint seems to link always with 'http://aksw.org/notInWiki/'.

**Comment by renespeck** [comment]
`curl --data-urlencode "text='<entity>Barack Obama</entity> is in <entity>Leipzig</entity>.'" -d type='agdistis' http://akswnc9.informatik.uni-leipzig.de:8114/AGDISTIS`

`[  
   {  
      "disambiguatedURL":"http:\/\/aksw.org\/notInWiki\/BarackObama",
      "offset":12,
      "namedEntity":"Barack Obama",
      "start":1
   },
   {  
      "disambiguatedURL":"http:\/\/aksw.org\/notInWiki\/Leipzig",
      "offset":7,
      "namedEntity":"Leipzig",
      "start":20
   }
]`

**Comment by RicardoUsbeck** [comment]
@renespeck or @DiegoMoussallem can you please ping Carl/Paul on Slack? I guess the wrong index is attached

**Comment by DiegoMoussallem** [comment]
Hi, @renespeck and @RicardoUsbeck , 

I did it and waiting for an answer.

**Comment by DiegoMoussallem** [comment]
@renespeck and @RicardoUsbeck it should be working now. Please check it.

**Comment by renespeck** [comment]
Great thanks. :+1:
