### ISSUE TITLE
Runtime 2min

### ISSUE THREAD

**Issue by renespeck** [dice-group/AGDISTIS#73]
Hi, for the German version, Agdistis needs up to 2min or more to process a couple of sentences. That's normal? 

For a very small one, it needs betweeen 10 and 20s.

`curl -w 'Total: %{time_total}s\n' --data-urlencode "text='<entity>Barack Obama</entity> is in <entity>Leipzig</entity>.'" -d type='agdistis' http://akswnc9.informatik.uni-leipzig.de:8114/AGDISTIS
`

**Comment by DiegoMoussallem** [comment]
Hey, it is not, our docker's server was struggling with memory issues some time ago. That might be the case.

**Comment by renespeck** [comment]
Hi thanks for the info, so will it be fixed sooner or later?

**Comment by DiegoMoussallem** [comment]
I asked Carl to have a look at it as soon as possible and I came to you with an answer.

**Comment by renespeck** [comment]
Hi, it seems that the online service produces a timeout within the FOX service (after 2 min without a response from Agdistis) 

The example in the first comment needs 68s. Longer text needs much longer time. 

Cheers.

**Comment by DiegoMoussallem** [comment]
resolved?
