### ISSUE TITLE
All candidates for named entity

### ISSUE THREAD

**Issue by pakaiser** [dice-group/AGDISTIS#74]
Request with type candidates returns to named entity all candidates, also the candidates for other marked entities.

curl --data-urlencode "text='<entity>Barack Obama</entity> visited <entity>Oracle</entity> Headquarter.'" -d type='candidates' http://akswnc9.informatik.uni-leipzig.de:8113/AGDISTIS

[
    {
        "Candidates":"[
            Candidates [StartPosition=1, Uri=http:\/\/dbpedia.org\/resource\/Barack_Obama, Score=0.03090146206084795], 
            Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle, Score=0.0]
        ]",
        "namedEntity":"Oracle"
    },
    {
        "Candidates":"[
            Candidates [StartPosition=1, Uri=http:\/\/dbpedia.org\/resource\/Barack_Obama, Score=0.03090146206084795], 
            Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle, Score=0.0]
        ]",
        "namedEntity":"Barack Obama"
    }
]

I would only expect Barack_Obama candidate for Barack Obama entity without Oracle candidate. The same with Oracle.

**Comment by DiegoMoussallem** [comment]
@vdanielupb Could you take a look?

**Comment by vdanielupb** [comment]
@DiegoMoussallem should be fixed with the last commit in master

**Comment by RicardoUsbeck** [comment]
What is the status here?

**Comment by DiegoMoussallem** [comment]
Working :)

> [{
	"Candidates": "[Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Githead, Score=0.017928911172473853], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle_Corporation, Score=0.003468671844675206], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle_Arena, Score=0.0034610335075038476], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/ORACLE_(teletext), Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/O-Force, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/The_Oracle_(University_of_South_Florida), Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle_(rocket), Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Nechung_Oracle, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/The_Oracle,_Queensland, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/The_Oracle,_Reading, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/The_Oracle_of_Reason, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/The_Oracle_(The_Matrix), Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle_machine, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Barbara_Gordon, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Internet_Oracle, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle_bone_script, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle_(Marvel_Comics), Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Random_oracle, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/The_Oracle_(Sweet_Valley), Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle_(comics), Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/ORACLE_(computer), Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/The_Oracle_(novel), Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle,_Arizona, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle_bone, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle_(workhouse), Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle_(software_testing), Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Oracle_Team_USA, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/San_Francisco_Oracle, Score=0.0], Candidates [StartPosition=22, Uri=http:\/\/dbpedia.org\/resource\/Padding_oracle_attack, Score=0.0]]",
	"namedEntity": "Oracle"
}, {
	"Candidates": "[Candidates [StartPosition=1, Uri=http:\/\/dbpedia.org\/resource\/Barack_Obama, Score=0.010960007199624658]]",
	"namedEntity": "Barack Obama"
}]
