### ISSUE TITLE
Fox moved 

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/AGDISTIS#76]
https://fox.demos.dice-research.org/#!/home
=> change URL in the deployed demo

**Comment by DiegoMoussallem** [comment]
We are moving all of our demos, so we are going to take of it as well

**Comment by RicardoUsbeck** [comment]
that makes it worse, I am afraid. Will there be a redirect? All the paper links will break

**Comment by DiegoMoussallem** [comment]
@bigerl he is the right person to answer your question

**Comment by bigerl** [comment]
We are on it.

**Comment by bigerl** [comment]
Redirection from https://fox-demo.aksw.org/ should be working now. @RicardoUsbeck please verify it and close the issue if it is fine.

**Comment by RicardoUsbeck** [comment]
It works (not yet in GERBIL though) ;) Thank you

**Comment by bigerl** [comment]
As far as I see it, GERBIL still runs on the AKSW address.

**Comment by RicardoUsbeck** [comment]
Maybe our ol' friend @TortugaAttack has some time please?

**Comment by TortugaAttack** [comment]
Can do :D 
What is the API endpoint?  or is the url the also the api endpoint?
previously: `http://IP:PORT/call/ner/entities`

**Comment by RicardoUsbeck** [comment]
I guess the  url is the  api endpoint

**Comment by TortugaAttack** [comment]
ok, will try to squeeze it into today :)

**Comment by RicardoUsbeck** [comment]
Thank you very much, really appreciate it, stay safe

**Comment by TortugaAttack** [comment]
Took a while due to other non work related stuff. 
URL change is commited, but will test it tomorrow before i restart Gerbil

**Comment by TortugaAttack** [comment]
It is not the url. 
Without the actual API URL i cannot do much :/ 
According to the documentation it something like https://fox.demos.dice-research.org:4444/fox 
I'll try to figure the url out.

**Comment by RicardoUsbeck** [comment]
@renespeck can you help?

**Comment by TortugaAttack** [comment]
he already did :)

**Comment by renespeck** [comment]
https://fox.demos.dice-research.org/fox
